spring.application.name=Project

server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.apvzthbzzwoltdeqdirx
spring.datasource.password=KBansal@5267
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql: true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bansalkeshav1390@gmail.com
spring.mail.password=mywe shdo bten anhc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#KESHAV BANSAL

razorpay.api.key=rzp_test_2iiLiUOeRszSMh
razorpay.api.secret=sJbptRgro4rHIDpW3Hb5tzW6